SharePoint/PnP-JS-Core

- docs/getting-started.md
The installation of python is only required on windows. I added the details to the get started guide.
> Update details to python installation on windows

- docs/api/pnp.md
- docs/api/sharepoint/provisioning/provisioning.md
- docs/api/sharepoint/rest/rest.md
- docs/api/sharepoint/sharepoint.md
Initial commit of sharepoint documentation. Want to start out small and make sure the structure is correct.
> Initial commit of sharepoint documentation

- .vscode/settings.json
- gulpfile.js
- jsconfig.json
- src/sharepoint/provisioning/core/core.ts
- src/sharepoint/provisioning/logger/logger.ts
- src/sharepoint/provisioning/objecthandlers/objectcomposedlook/objectcomposedlook.ts
- src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts
- src/sharepoint/provisioning/objecthandlers/objectlists/objectlists.ts
- src/sharepoint/provisioning/objecthandlers/objectnavigation/objectnavigation.ts
- src/sharepoint/provisioning/objecthandlers/objectpropertybagentries/objectpropertybagentries.ts
- src/sharepoint/rest/Queryable.ts
- src/sharepoint/rest/web/lists/contenttypes/contenttypes.test.ts
- src/sharepoint/rest/web/lists/contenttypes/contenttypes.ts
- src/sharepoint/rest/web/lists/items/items.ts
- src/sharepoint/rest/web/lists/lists.ts
- src/sharepoint/rest/web/lists/views/views.ts
- src/sharepoint/util.ts
- tsconfig.json
Just pulled the repo and saw that ```gulp test``` didn't work. That made me sad.
Seems the implementation files were referencing an invalid location.
I like the idea behind this repo. I'l be back after I go learn typescript.
> Reference ../utils/util instead of /Util (which doesn't seem to exist)

- docs/api/configuration/IConfigurationProvider.md
- docs/api/configuration/configuration.md
- docs/api/configuration/providers/cachingConfigurationProvider.md
- docs/api/configuration/providers/providers.md
- docs/api/configuration/providers/spListConfigurationProvider.md
- docs/api/configuration/settings.md
- docs/api/pnp.md
- src/configuration/configuration.ts
- src/configuration/providers/cachingConfigurationProvider.ts
- src/configuration/providers/spListConfigurationProvider.ts
Added initial API documentation for configuration providers.
> Documentation for ConfigurationProviders

- src/sharepoint/sharepoint.ts
Could not find src/sharepoint/util exposed anywhere in the API
> Expose pnp.sharepoint.util as public

- docs/api/pnp.md
- docs/api/sharepoint/rest/rest.md
- docs/api/sharepoint/rest/web.md
- docs/api/utils/storage.md
- docs/api/utils/util.md
Document util.extend
Document storage
Document sharepoint/rest/rest
Document sharepoint/rest/web
> More documentation

- README.md
- docs/api/readme.md
- docs/getpnp.md
- docs/getting-started.md
- docs/readme.md
- Added `npm install sp-pnp-js` to documentation since it was asked about in [Yammer](https://www.yammer.com/itpronetwork/#/Threads/show?threadId=688861358)
- Added temporary text to key landing page indicating this library is not production yet (to make it very clear about our current status)
- Fixed broken links to current api documentation in a couple pages
> Minor documentation updates

- src/utils/logging.ts
- src/utils/storage.ts
- tests/utils/logging.test.ts
- tests/utils/storage.test.ts
Updates and usability improvements based on sample creation.
> Updates to logging, added async support to getOrPut in storage wrapper.

- src/sharepoint/provisioning/core/core.ts
- src/sharepoint/provisioning/objecthandlers/objectcustomactions/objectcustomactions.ts
- src/sharepoint/provisioning/objecthandlers/objecthandlerbase/objecthandlerbase.ts
- src/sharepoint/provisioning/objecthandlers/objectlists/objectlists.ts
- src/sharepoint/provisioning/objecthandlers/objectnavigation/objectnavigation.ts
- src/sharepoint/provisioning/sequencer/sequencer.ts
- src/sharepoint/util.ts
Fixing #74 , as in its comments.
Not every reference has been removed yet!
> Remove remaining jQuery refs in src 

- buildtasks/sync.js
- gulpfile.js
Added gulp task 'Sync' to copy pnp.js to sharepoint when source files change.
> Add Sync to Sharepoint task

- src/sharepoint/rest/fields.ts
- tests/sharepoint/rest/fields.test.ts
Hi,
I add Field class missing members (properties) and tests to support the implementation.
Would you please review the changes.
> Adds Field class missing members and tests to support them.

- src/sharepoint/provisioning/objecthandlers/objectcomposedlook.ts
- src/sharepoint/provisioning/objecthandlers/objectcustomactions.ts
- src/sharepoint/provisioning/objecthandlers/objectfeatures.ts
- src/sharepoint/provisioning/objecthandlers/objectfiles.ts
- src/sharepoint/provisioning/objecthandlers/objecthandlerbase.ts
- src/sharepoint/provisioning/objecthandlers/objectlists.ts
- src/sharepoint/provisioning/objecthandlers/objectnavigation.ts
- src/sharepoint/provisioning/objecthandlers/objectpropertybagentries.ts
- src/sharepoint/provisioning/objecthandlers/objectwebsettings.ts
- src/sharepoint/provisioning/provisioning.ts
- src/sharepoint/provisioning/provisioningstep.ts
- src/sharepoint/provisioning/sequencer/sequencer.ts
| Bug fix?        | NO
| New feature?    | In a way? It's documentation
This is a initial commit for documentation of the sharepoint\provisioning part that I've merged from https://github.com/Puzzlepart/js-sites-core.
> Added initial documentation to sharepoint\provisioning

- src/sharepoint/provisioning/objecthandlers/objecthandlerbase.ts
- src/sharepoint/provisioning/objecthandlers/objectnavigation.ts
- src/sharepoint/provisioning/provisioning.ts
- src/sharepoint/provisioning/sequencer/sequencer.ts
- src/sharepoint/provisioning/util.ts
| Related issues?  |
Fixing a Promise bug in pnp\sp\provisioning
> pnp\sp\provisioning: start(), need to resolve the first promise

- src/sharepoint/provisioning/sequencer/sequencer.ts
| New feature?    | yes, optional progressFunction callback so caller can report progress
Simplified code for running an Array of (Promise) functions in Sequence
Inlined TS private declarations on constructor so Private variables don't have to be specified twice
Simplified executor function to use a promise chain
Single reference (const) to this for readablity and better minification
Optional progressFunction Callback runs with the Sequencer as scope and uses variables:
- last functionNr that wa resolved
- array of all functions
Note: Provisioning seems to run a array of functions as well, it needs further investigation of this Sequencer can be used …
> Simplified Sequencer code

- server-root/index.html
- server-root/scratchpad.js
- src/sharepoint/rest/sitegroups.ts
- src/sharepoint/rest/siteusers.ts
- src/sharepoint/rest/webs.ts
- tests/sharepoint/rest/sitegroups.test.ts
- tests/sharepoint/rest/siteusers.test.ts
| Related issues?  | Closes out #55 
Adds support for Users, Groups, and formats json during dev as pictured here
Every method tested, all tests passing, tslint passing.
It is recommended that you update your "script snippet" in SharePoint with the updated boilerplate from index.html.  Without it JSON will still be prettified, but syntax highlighting won't work because the styles are missing.
Moved jquery to use a cdn instead of having to copy it to SharePoint.
Does not include the apis for UserCustomAction or RoleAssignments.  Recommend adding issues for help wanted.
> Adds support for Users, Groups, and formats json during dev

- src/pnp.ts
| Bug fix?        |  Yes
| Related issues?  | fixes #116 
This PR updates pnp.ts to fix the issue reported in #116.
> fix for issue 116

- AUTHORS
> updates to authors file

- .gitignore
- bower.json
| Bug fix?        | no - yes?
| New feature?    | no - yes?
> updates for bower packaging

- buildtasks/copyJsToSharePoint.js
- package.json
| New feature?    | no 
| Related issues?  | fixes #139 
Closes #139
> Updated dependency to spsave 2.x.

- .bithoundrc
- .npmignore
- bower.json
Added a .bithoundrc to help control the analysis of the repo by bithound. Also updated the bower and npm ignore settings to not include said file.
> adding .bithoundrc file for ignoring certain folders in bithound

- src/sharepoint/rest/webs.ts
Include Web.Fields and Web.AvailableFields properties to retrieve the field collection from SharePoint website
**Web.Fields**
`$pnp.sp.web.fields.get().then(function(result){ console.log(result); });`
**Web.AvailableFields**
`$pnp.sp.web.availablefields.get().then(function(result){ console.log(result); });`
**Author**
Shantha Kumar T
> Adding fields and availablefields support to web object

- src/sharepoint/rest/userprofiles.ts
| Related issues?  | Fixes #157 
Fixes an issue with the URL in one of the user profile methods missing the "_api" part.
> Fix for issues #157

- gulpfile.js
| Related issues?  | #146
Makes updates to the header of the packaged files to include more information.
> update to header to close issue #146

- src/sharepoint/rest/roles.ts
| Related issues?  | As fixed in #145 but cleaned up to only include relevant files
> making update from PR #145 that doesn't include all of the files

- src/sharepoint/rest/lists.ts
| Bug fix?        | no 
| Related issues?  | no
Adding quick description in [getItemsByCAMLQueryParams](https://github.com/mauricionr/PnP-JS-Core/blob/getItemsByCAMLQueryParams/src/sharepoint/rest/lists.ts#L314)
> Get items by caml query params

- README.md
| Related issues?  | no
Adds animated gif to readme showing how library is used.
> Adds animated gif showing library usage to readme.md

- package.json
- src/collections/collections.ts
- src/configuration/configuration.ts
- src/configuration/pnplibconfig.ts
- src/net/HttpClient.ts
- src/net/NodeFetchClient.ts
- src/sharepoint/rest/caching.ts
- src/sharepoint/rest/lists.ts
- src/sharepoint/rest/odata.ts
- src/sharepoint/rest/queryable.ts
- src/sharepoint/rest/roles.ts
- src/sharepoint/rest/search.ts
- src/sharepoint/rest/sitegroups.ts
- src/sharepoint/rest/userprofiles.ts
- src/sharepoint/rest/views.ts
- src/utils/storage.ts
> Updates to clear tslint errors from new version

- src/net/nodefetchclient.ts
Bug fix for client secrets that contain special characters. For more information check [issue 208](https://github.com/OfficeDev/PnP-JS-Core/issues/208).
> Bug fix for client secrets with special characters

- tests/test-config.test.ts
| Bug fix?        | no - yes?
| New feature?    | no - yes?
> commenting out delete all subsites in testing method

- src/sharepoint/rest/files.ts
- src/sharepoint/rest/index.ts
- src/sharepoint/rest/queryable.ts
| New feature?    | Yes
| Related issues?  | Addresses #214 
Increased support for getting and updating files through REST
> Adding better file support for adding and updating files

- src/sharepoint/rest/files.ts
- src/sharepoint/rest/items.ts
- src/sharepoint/rest/odata.ts
- src/sharepoint/rest/queryable.ts
| Related issues?  | Fixes #231 
Updates to fix issue 231 related to paged item collection with odata verbose
> Updates to fix issue 231 related to paged item collection with odata verbose

- package.json
| Bug fix?        | no - yes?
| New feature?    | no - yes?
> updating git repo url after transfer

- README.md
- src/sharepoint/rest/index.ts
- src/sharepoint/rest/rest.ts
- src/sharepoint/rest/searchsuggest.ts
| New feature?    |  yes
| Related issues?  | #238 
adding support for the search/suggest api as per issue 238
> adding support for the search/suggest api as per issue 238

- src/sharepoint/rest/search.ts
| Related issues?  | fixes #241 
Update to make refiners a string value on the search input object
> fix for issue #241

- src/sharepoint/rest/odata.ts
- src/sharepoint/rest/queryable.ts
- src/sharepoint/rest/rest.ts
- src/sharepoint/rest/site.ts
- src/sharepoint/rest/webs.ts
- src/utils/util.ts
| Related issues?  | fixes #249 
Adds a createBatch method to both Web and Site objects allowing for the proper scoping of batches on instances created directly using these objects.
> fix for issue 249 and batch support for Web and Site used directly

- src/sharepoint/rest/files.ts
- src/sharepoint/rest/index.ts
| Related issues?  | fixes #257
Adding a getJSON method to File as mentioned in #257
> Adding a getJSON method to File as mentioned in #257

- tests/sharepoint/rest/files.test.ts
| Bug fix?        | no - yes?
| New feature?    | no - yes?
> Fixed a broken test - files, value was missing

- src/net/sprequestexecutorclient.ts
| Related issues?  | fixes #256 
Updates the code to handle a 204 body in the SPRequestExecutor.
> Fix for #256

- src/sharepoint/rest/queryablesecurable.ts
Fixed comment for resetRoleInheritance (was a duplicate of breakRoleInheritance)
> Fixed resetRoleInheritance documentation

- src/net/httpclient.ts
- src/sharepoint/rest/usercustomactions.ts
| Bug fix?        | [ x]
| New feature?    | [x ]
**UserCustomActions**, method **getById** does not return anything. It is requesting **_api/web/usercustomactions/('a605f1ac-ff47-41e9-bf9e-100fe39b544c')** which is wrong. 
The correct url is **_api/web/usercustomactions('a605f1ac-ff47-41e9-bf9e-100fe39b544c')** without **/** in between. This PR will fix that.
Also Implemented **delete** method for UserCustomAction class
Also added implementation to get proper error message when fetch succeeds but response.ok == false
> UserCustomAction method getById does not return anything, heres a fix for that.

- .gitignore
- src/net/sprequestexecutorclient.ts
- src/sharepoint/rest/attachmentfiles.ts
- src/sharepoint/rest/usercustomactions.ts
- src/utils/util.ts
| Bug fix?        | [ X]
| Related issues?  Unknown
Got an error when I built master about types, so I tried the dev branch and got the same error.  The build is now succeeding and the tests are passing.
**PR also Includes:**
- Fixed a typo
- Fixed TSLint warnings (a var -> let and whitespace)
- Added yarn.lock to .gitignore
> Fixes build errors in Utils.extend

- src/utils/exceptions.ts
- tsconfig.json
- webpack-serve.config.js
| Bug fix?        | [ X]
| Related issues?  | fixes #281
Greatly simplifies the exception objects and removes the base class which supplied little value.
> Fix for #281

- .vscode/launch.json
- src/sharepoint/contenttypes.ts
- src/sharepoint/items.ts
> Add FieldLinks and file property to item

- README.md
> moving image down on readme

- src/sharepoint/items.ts
- src/sharepoint/lists.ts
- src/sharepoint/queryablesecurable.ts
> Adding support for passing in the ListItemEntityTypeName

- src/sharepoint/files.ts
| Related issues?  | fixes #305 
Fixes the File class's listItemAllFields property as it should not return an full Item instance.
> Fix for issue 305

- src/sharepoint/files.ts
- src/sharepoint/webparts.ts
- src/sharepoint/webs.ts
Adds basic support for working with webparts by expanding the limited web part manager.
> adding basic support for working with webparts

- .vscode/launch.json
- .vscode/tasks.json
- jsdoc.json
- src/configuration/pnplibconfig.ts
- src/sharepoint/attachmentfiles.ts
- src/sharepoint/files.ts
- src/sharepoint/folders.ts
- src/sharepoint/odata.ts
- src/sharepoint/queryable.ts
- src/utils/decorators.ts
- src/utils/exceptions.ts
- src/utils/util.ts
- tsconfig.json
| Related issues?  | fixes #313 
Updates the request pipeline and setup to allow passing of an SPFx context or set a baseUrl.
Also adds support for pre & post request actions that in a future release can become extension points for the library
> Updates to request pipeline

- gulptasks/serve.js
- src/sharepoint/files.ts
- src/sharepoint/lists.ts
- src/sharepoint/odata.ts
- src/sharepoint/queryable.ts
- src/sharepoint/queryablerequest.ts
- src/utils/logging.ts
- tests/sharepoint/lists.test.ts
Full update to request pipeline as step one in making the entire request chain extensible.
Other updates/fixes/typos
> full rewrite of request pipeline, move to a sep. file

- src/sharepoint/odata.ts
- src/sharepoint/queryablerequest.ts
Additional logging, code clean-up, updates from final testing
> Additional logging, code clean-up, updates from final testing

- src/sharepoint/items.ts
- tests/sharepoint/errors.test.ts
| Related issues?  | fixes #328
Provides a fix and adds tests to cover eating errors in the list item add/update methods.
> Fix for #328, item update is eating errors

- package.json
- src/net/httpclient.ts
- src/net/sprequestexecutorclient.ts
- tsconfig.json
| Related issues?  | fixes #331 
Makes updates to work with TS 2.2.1 where types for fetch were introduced to the core .d.ts file for es6.
> fixing issue 331

- src/sharepoint/fields.ts
> demo travis

- src/net/digestcache.ts
- src/sharepoint/lists.ts
| Related issues?  | fixes #345 
> Fix for 345 and fixes for lists.ensure and .add behaviors

- .babelrc
- gulptasks/@configuration.js
- package.json
- tsconfig.json
- webpack.config.js
> rolling back to es5 in /lib folder

- tsconfig.json
> fixing broken build due to breaking change in core-js def file

- src/sharepoint/siteusers.ts
> fixing quoting issue for login name in query string

- tests/sharepoint/siteusers.test.ts
> fixing bug in test after change in siteusers

- src/sharepoint/odata.ts
| Related issues?  | fixes #377
Fixes #377
> fixing #377

- src/sharepoint/attachmentfiles.ts
- src/sharepoint/contenttypes.ts
- src/sharepoint/features.ts
- src/sharepoint/fields.ts
- src/sharepoint/files.ts
- src/sharepoint/folders.ts
- src/sharepoint/forms.ts
- src/sharepoint/index.ts
- src/sharepoint/items.ts
- src/sharepoint/lists.ts
- src/sharepoint/navigation.ts
- src/sharepoint/queryable.ts
- src/sharepoint/queryablesecurable.ts
- src/sharepoint/roles.ts
- src/sharepoint/sitegroups.ts
- src/sharepoint/siteusers.ts
- src/sharepoint/subscriptions.ts
- src/sharepoint/usercustomactions.ts
- src/sharepoint/userprofiles.ts
- src/sharepoint/views.ts
- src/sharepoint/webparts.ts
- src/sharepoint/webs.ts
| Related issues?  | fixes #380
Fixes methods that created a new instance and executed a request within the method - meaning any batch was lost. See web.ensureUser as the base case.
> Fix for #380

- src/sharepoint/queryablesecurable.ts
- src/sharepoint/types.ts
- src/sharepoint/webs.ts
Provides better support for getting user's permissions for a given securable.
> Adding better support for determining user's permissions

- src/configuration/pnplibconfig.ts
- src/sharepoint/fields.ts
- src/sharepoint/files.ts
- src/sharepoint/folders.ts
- src/sharepoint/items.ts
- src/sharepoint/odata.ts
- src/sharepoint/queryable.ts
- src/sharepoint/queryablerequest.ts
- src/sharepoint/queryableshareable.ts
- src/sharepoint/rest.ts
- src/sharepoint/sharing.ts
- src/sharepoint/types.ts
- src/sharepoint/userprofiles.ts
- src/sharepoint/webs.ts
- src/utils/storage.ts
- tests/mocks/mockstorage.ts
- tests/sharepoint/sharing.test.ts
| Related issues?  | fixes #389 
Sharing, added getItem to file and folder, added associated groups to web, update default cache timeout
> Sharing + additional updates

- tests/sharepoint/sharing.test.ts
> commenting out breaking tests across versions

- src/sharepoint/queryable.ts
| Related issues?  | fixes #395 
> adding support for alias parameters globally

- src/sharepoint/queryable.ts
- tests/sharepoint/alias.test.ts
> fixing lint error, also adding tests for parameter aliasing

- src/sharepoint/odata.ts
| Related issues?  | fixes #392
Updated handling of batch dependency promises to resolve issue #392
> Updated handling of batch dependency promises to resolve issue #392

- gulptasks/test.js
- gulptasks/travisci.js
fixing testing process exit issue causing travisci builds to hang
> fixing testing process exit issue causing travisci builds to hang

- .travis.yml
- gulptasks/publish.js
- gulptasks/travisci.js
- package.json
| Related issues?  | fixes #379 
Adds support for creating a scripted beta release, but not yet done from Travis.
> Support for scripted dev branch release as beta

- src/sharepoint/webs.ts
| New feature?    | [ x]
Support for web/webinfos.
> Support for web/webinfos

- src/pnp.ts
- src/sharepoint/index.ts
- src/sharepoint/rest.ts
- src/sharepoint/types.ts
- src/sharepoint/utilities.ts
| Related issues?  | adds support requested in #425 
Adds support for static utility methods
> Adding support for utility methods as exposed from SP.Utilities.Utility

- debug/debug.ts
- src/sharepoint/index.ts
- src/sharepoint/rest.ts
- src/sharepoint/search.ts
| Related issues?  | fixes #271 
Adds support for a fluent search query builder as well as additional typing support for search related interfaces.
> Adds fluent search query builder and additional search interfaces

- src/sharepoint/siteusers.ts
| Related issues?  | None
Minor documentation updates/fixes
> Minor documentation updates/fixes

- src/sharepoint/usercustomactions.ts
| Related issues?  | None
Minor documentation fixes/updates
> Minor documentation fixes/updates

- src/sharepoint/queryableshareable.ts
| Related issues?  | fixes #450 
Updates the tertiary statement to correctly use the value if it is provided.
> Fix for #450

- src/sharepoint/index.ts
- src/sharepoint/roles.ts
- src/sharepoint/webparts.ts
- src/sharepoint/webs.ts
| Related issues?  | fixes #458
Adds additional methods to the WebPartDefinition and fixes some linting errors from pervious PRs
> add additional WebPartDefinition methods, fix linting errors

- src/sharepoint/search.ts
| Related issues?  | fixes #462
This fixes the issue reported in #462.
> Fix for 462

- src/sharepoint/items.ts
| Related issues?  | fixes #466 
Fixes an issue with non-verbose mode result for the getWOPIUrl method.
> Fix for 466 with fix to handle verbose mode in getWPOI Url

- src/utils/util.ts
| Related issues?  | fixes #438 
Adds a requested feature to process the siteassets path when determining the absolute url
> adding support for siteassets path

- debug/debug.ts
- src/net/httpclient.ts
- src/sharepoint/odata.ts
| Related issues?  | fixes #492
Fixes the case where headers with different cases are added that overlap the defaults (Accept, Content-Type) - i.e. someone specifies "accept" and then the library adds "Accept". This only affected batches as they processed headers differently.
> Fix for #492

- src/sharepoint/queryablesecurable.ts
| Related issues?  | fixes #509
Fixes a bug where permissions are not calculated correctly in verbose mode.
> Fix for #509 - handle verbose mode for getUserEffectivePermissions

- src/sharepoint/search.ts
| Related issues?  | fixes #524 
Fixes the casing for some SearchQuery properties.
> Fix for #524 - correcting casing for SearchQuery properties

- package.json
- src/sharepoint/attachmentfiles.ts
- src/sharepoint/contenttypes.ts
- src/sharepoint/features.ts
- src/sharepoint/fields.ts
- src/sharepoint/files.ts
- src/sharepoint/folders.ts
- src/sharepoint/items.ts
- src/sharepoint/lists.ts
- src/sharepoint/navigation.ts
- src/sharepoint/queryable.ts
- src/sharepoint/queryablesecurable.ts
- src/sharepoint/queryableshareable.ts
- src/sharepoint/relateditems.ts
- src/sharepoint/roles.ts
- src/sharepoint/search.ts
- src/sharepoint/site.ts
- src/sharepoint/sitegroups.ts
- src/sharepoint/siteusers.ts
- src/sharepoint/subscriptions.ts
- src/sharepoint/usercustomactions.ts
- src/sharepoint/userprofiles.ts
- src/sharepoint/utilities.ts
- src/sharepoint/views.ts
- src/sharepoint/webparts.ts
- src/sharepoint/webs.ts
| Related issues?  | fixes #526
makes updates required for the library to build against the latest TS version 2.4.1.
> Updates to support TypeScript 2.4.1

- package.json
Updates the gulp-typescript ref in the project. Closes #528.
> Updated gulp-typescript version now that dependant issue was fixed.

- src/sharepoint/index.ts
| Related issues?  | fixes #542 
Adds the FIle and Files object to the global exports.
> Adding File and Files to the global exports

- src/sharepoint/search.ts
| Related issues?  | fixes #535
Makes the change suggested in #535 to address an issue with getPage
> Fix as suggested in #535

- src/configuration/pnplibconfig.ts
- src/sharepoint/views.ts
- src/utils/logging.ts
- src/utils/storage.ts
| Related issues?  | Adds support discussed in #555 
Adds support for removing expired items from the cache as [documented here](
https://github.com/SharePoint/PnP-JS-Core/wiki/Caching#cache-expiration).
> Update to support removing expired items from cache

- src/net/sprequestexecutorclient.ts
| Related issues?  | fixes #565
This adds a check in the request executor client to see what methods we are calling and set the binary request flag if it seems like it would be needed.
> fix for #565

- src/sharepoint/lists.ts
- src/sharepoint/types.ts
| Related issues?  | as mentioned in #584
adding support for list.RenderListDataAsStream
> adding support for list.RenderListDataAsStream

- debug/debug.ts
- package.json
| Related issues?  | mentioned in #600
Adds the graph types as a package dependency, which was missed.
> adding missing graph type to package dependency

- gulptasks/build.js
- src/exports/core.ts
| Related issues?  | fixes #603
Adds requested exports.
> Adding exports for storage classes

- src/sharepoint/webs.ts
- tests/sharepoint/web.test.ts
This PR adds implementation for `/_api/web/SiteUserInfoList` endpoint.
> SiteUserInfoList endpoint implementation

- src/sharepoint/utilities.ts
Cleans up the "create" method from the utilities class in favor of the shared clone method.
> clean up utlities to use shared clone method

- src/sharepoint/regionalsettings.ts
- tests/sharepoint/regionalsettings.test.ts
| Related issues?  | fixes #659 
Update to fix issue with date calc in method
> patch for calculating the date for regional settings

- src/sharepoint/navigation.ts
- src/sharepoint/rest.ts
- src/sharepoint/types.ts
| Related issues?  | mentioned in #667 
Adds support for the navigation service. Also updated a [wiki entry ](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Navigation-Service) describing functionality.
> support for navigation service as discussed in #667

- src/sharepoint/webs.ts
| Related issues?  | #590 
Adds support for the allproperties collection as a property on the web object
> adds the allproperties property to web

- src/sharepoint/index.ts
- src/sharepoint/items.ts
| Bug fix?        | []
| Related issues?  | addresses #700 & #689
Exports Field and Fields objects from library. Adds a new method getAll to items collection. See #689 thread for sample usage until wiki is updated.
> Add Field and Fields exports, Add getAll method to items collection

- src/sharepoint/fields.ts
| Related issues?  | fixes #704 
updated typing for field properties to include any
> updated typing for field properties to include any

- README.md
Updates the readme with a message on the future of sp-pnp-js
> update to readme for message on future of sp-pnp-js

- src/sharepoint/sharepointqueryable.ts
- tests/sharepoint/configure.test.ts
Closes #735
| Related issues?  | fixes #735 
Fix for `configure` method and `clone` combination.
> Added fix for clone method.

- src/sharepoint/clientsidepages.ts
| Related issues?  | fixes #740 (possibly)
Moving over the updates for clientsidepages module from @pnp/sp.
> Moving over clientsidepage updates from @pnp/sp

- src/sharepoint/types.ts
- src/sharepoint/userprofiles.ts
| Related issues?  | #749
Added support for ClientPeoplePickerWebServiceInterface solving #749.
> Added support for ClientPeoplePickerWebServiceInterface

- src/sharepoint/search.ts
| Related issues?  | fixes #766
Fixes a typo in an enum name.
> fix for 766

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
| Q                        | A
| ------------------ | ---
| Bug fix?              | [ ]
| New feature?     | [ ]
| New sample?     | [ ]
| Related issues?  | fixes #768
Transition guidance link fix (it do not redirect to a new `https://pnp.github.io/pnpjs` area) and some tiny fixes in md's and github templates (decorations).
> Misc typos and link to pnp\pnpjs correction
