src/sharepoint/rest/web/lists/contenttypes/contenttypes.test.ts, src/sharepoint/rest/web/lists/contenttypes/contenttypes.ts, src/sharepoint/rest/web/lists/lists.ts, src/sharepoint/rest/web/lists/views/views.test.ts, src/sharepoint/rest/web/lists/views/views.ts
Support for ContentTypes and Views under Lists.
That's probably enough for Lists for now. We now support
- Items
- Views
- ContentTypes
Before doing more on the fluent api, I would like to know where to put usage documentation.
=> FLUENT API: Added support for ContentTypes and Views for Lists

README.md, docs/getting-started.md
This is in line with the gulp getting started guide found here: https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md
=> Add Gulp CLI install instructions

src/net/HttpClient.ts, src/sharepoint/rest/lists.ts
Does a retry inline with the same logic as the CSOM library on response status 429 and 503. Request retry follows curve, taking longer each pass as shown:
=> update to support retry on server unavailable or throttled request responses

bower.json, buildtasks/package.js, package.json, src/sharepoint/provisioning/objecthandlers/objectfiles.ts
This should close #74 , all calls / references to jQuery methods have been replaced with alternatives already present in the library :)
Also references from Gulp build and packages files have been removed
It needs some serious tests!
=> Remove remaining jQuery refs in src (objectFiles.ts) #2

buildtasks/package.js
The dist/pnp.d.ts TypeScript definition was getting created without member JSDoc comments present, which created a less than desired intellisense experience in code editors.
This custom gulp task fix just adds the appropriate setting to the TypeScript compiler to preserve the comments during the generation of the dist/pnp.d.ts TypeScript definition.
=> pnp.d.ts now gets created with member comments present

.npmignore, .vscode/settings.json, buildtasks/package.js, src/pnp.ts
| New sample?      | no 
| Related issues?  | fixes #88
This PR updates how the pnp library is exposed, removes the string replacements in build, and fixes an issue when including the library in other projects.
=> updates to expose pnp and pnp.default, removes string replace in package

src/sharepoint/rest/lists.ts, tests/sharepoint/rest/lists.test.ts
| Bug fix?        | not sure :)
Included a regex replace in lists.getById() in order to be able to use e.g. spPageContextInfo.pageListId directly. {} are replaced from the string.
Included a test.
=> Included a regex replace in lists.getById() in order to be able to use e.g. _spPageContextInfo.pageListId directly

typings.json
Typings has introduced a breaking change in 1.0.  ambient has been renamed to global.
See [Typings](https://github.com/typings/typings) for more information.
=> Fixes declarations not being installed with latest version of typings

src/pnp.ts, src/sharepoint/rest/contenttypes.ts, src/sharepoint/rest/files.ts, src/sharepoint/rest/folders.ts, src/sharepoint/rest/items.ts, src/sharepoint/rest/lists.ts, src/sharepoint/rest/queryableSecurable.ts, src/sharepoint/rest/quicklaunch.ts, src/sharepoint/rest/search.ts, src/sharepoint/rest/site.ts, src/sharepoint/rest/sitegroups.ts, src/sharepoint/rest/siteusers.ts, src/sharepoint/rest/topnavigationbar.ts, src/sharepoint/rest/userprofiles.ts, src/sharepoint/rest/views.ts, src/sharepoint/rest/webs.ts, src/utils/storage.ts
When testing in webpack warnings were noted that different casing was used in the various import statements. This PR normalizes these to all lowercase which will remove these warnings in the future.
=> normalizing module names in import statements

server-root/scratchpad.js, src/configuration/pnplibconfig.ts, src/net/DigestCache.ts, src/net/HttpClient.ts, src/pnp.ts, src/sharepoint/rest/odata.ts
| New feature?    | Yes
| Related issues?  | fixes #125 
This PR contains an update to provide global configuration of the headers sent with each REST request. This resolves #125 by allowing a developer to set "application/json; odata=verbose" for the accept header as shown below:
```
pnp.setup({
headers: {
"Accept": "application/json; odata=verbose"
}
});
pnp.sp.web.get().then(show);
```
This also enables the scenario of setting an authentication header using a previously retrieved bearer token - or any other headers that may be needed for a given solution. Currently "headers" is the only configurable property but we will add additional configuration options as they become required or found to …
=> Update to support config of headers sent in requests (issue #125)

src/sharepoint/rest/items.ts
Added new method for getting the WOPI frame url for an item.
See: https://msdn.microsoft.com/en-us/library/office/jj246933.aspx
Usage:
`...items.getById(1).getWopiFrameUrl().then(function(result) { ... });`
=> get wopi frame url of item

README.md, server-root/scratchpad.js, src/configuration/pnplibconfig.ts, src/net/HttpClient.ts, src/sharepoint/rest/caching.ts, src/sharepoint/rest/items.ts, src/sharepoint/rest/lists.ts, src/sharepoint/rest/odata.ts, src/sharepoint/rest/queryable.ts, src/sharepoint/rest/rest.ts, src/sharepoint/rest/userprofiles.ts, src/utils/util.ts, tslint.json
| New feature?    | Yes
| Related issues?  | None
This PR introduces batching and caching functionality to the library. These methods are composable and you can cache the results of batch requests. You can set global defaults for the caching parameters as well as globally disable caching, say for local testing. Also, the cache parameters can be set on a per call basis. The default cache key is the full request URI with query parameters, default storage is session, and the default timeout is 30 seconds.
```
let b = pnp.sp.createBatch();
pnp.sp.web.usingCaching().inBatch(b).get().then(...);
pnp.sp.web.lists.usingCaching({
expiration: new Date(2016, 6, 21),
key: "MyGreatUniqueKey",
storeName: …
```
=> Adding support for caching and batching to the library

src/configuration/pnplibconfig.ts, src/net/HttpClient.ts, src/net/SPRequestExecutorClient.ts
Support for CORS calls using the SP.RequestExecutor object, see Yammer discussion (https://www.yammer.com/itpronetwork/#/Threads/show?threadId=718329691).
Use pnp.setup( {  useSPRequestExecutor: true } ) to enable CORS, then use pnp.sp.crossDomainWeb to make the calls.
Include the /_layouts/15/SP.RequestExecutor.js in your page to have the SP.RequestExecutor available.
=> CORS support

src/net/HttpClient.ts
| Related issues?  | fixes #151
Adds a null check for the mergeHeaders method, which was throwing an error in Firefox.
=> fix for issue 151

buildtasks/lint.js, package.json
| New feature?    | Yes
Fixes an old version of the gulp-tslint library. Also updates the build task to account for new format as well as block the second error getting thrown to clean up UI during lint error reporting.
=> Update for gulp-tslint and associated build task to account for updates

src/sharepoint/rest/fields.ts
| Bug fix?        | no 
| New sample?      | no 
Include **Fields.getByInternalNameOrTitle** property to retrieve the field based on internal name or field display name from SharePoint website
$pnp.sp.web.fields.getByInternalNameOrTitle('fieldname').get().then(function(result){ console.log(result); });
####Author
Shantha Kumar T
(T)@ktskumar
=> Fieldproperties

package.json
| Related issues?  | fixes #185
The browser file reference in package.json seems to point to /build/ but should point to /lib/ instead.
./build folders aren't available in node_modules
=> do a package.json browser switcheroo

tests/sharepoint/rest/contenttypes.test.ts, tests/sharepoint/rest/fields.test.ts, tests/sharepoint/rest/files.test.ts, tests/sharepoint/rest/folders.test.ts, tests/sharepoint/rest/items.test.ts, tests/sharepoint/rest/lists.test.ts, tests/sharepoint/rest/navigation.test.ts, tests/sharepoint/rest/quicklaunch.test.ts, tests/sharepoint/rest/roles.test.ts, tests/sharepoint/rest/sitegroups.test.ts, tests/sharepoint/rest/siteusers.test.ts, tests/sharepoint/rest/topnavigationbar.test.ts, tests/sharepoint/rest/views.test.ts, tests/sharepoint/rest/web.test.ts, tests/test-config.test.ts, tests/testutils.ts
This PR fixes the static url tests which were broken when the code was updated to make the urls absolute when using the node request client. Change was to match the end of the url using regex instead of equals.
=> updates to fix tests when web tests are enabled and url is made absolute

src/sharepoint/rest/webs.ts, tests/sharepoint/rest/web.test.ts
This PR adds capability to use web's getList method for getting list base on its relative URL, which is more preferable in compare to pnp.sp.web.lists.getByTitle and simpler to maintain that pnp.sp.web.lists.getById.
Extends REST API wrapper with web.getList, which allows getting access for the following construction:
pnp.sp.web.getList('/sites/site/lists/customlist')
=> Web is extended with getList method for retrieving lists by Url

src/sharepoint/rest/queryable.ts, tests/sharepoint/rest/queryable.test.ts
| Related issues?  | fixes #198
Order by behavior fix.
`When calling pnp.sp.web.list.get().items.orderBy('Id', false) the REST query should contain $orderby=Id desc.
Currently the second parameter in the orderBy function determines whether sorting should be done ascending. Given that that's the default setting, consider changing the second parameter to descending so that when set, it explicitly adds desc to the $orderby clause in the REST query.`
Descending was a default order due to the description.
Because desc was not added to the api url parameter this didn't work.
With working descending parameters I consider asc to be a default one.
```javascript
// descending …
```
=> Unable to sort items descending #198 fix

src/sharepoint/rest/contenttypes.ts
I've added the following REST API call to the ContentTypes class: addAvailableContentType (https://msdn.microsoft.com/en-us/library/office/jj246551.aspx).
I've tested the code on SPO with the following code: 
`$pnp.sp.web.lists.getByTitle("TestCT").contentTypes.addAvailableContentType("0x010102");`
I was wondering if it's also possible to create a contenttype using the PnP-JS-Core library. For now I'm using the CSOM version to create the contenttypes and then I can use the above method to add the created CT to a list. But it would be nice if it was possible to create a CT using pure REST.
=> Added addAvailableContentType REST method to the ContentTypes class

src/utils/storage.ts
| Related issues?  | fixes #245 
Fixes a bug where passing an expire value to getOrPut in storage wrapper was not passed on as expected.
=> Fix for issue #245, not passing expire in getOrPut of storage wrapper

src/net/sprequestexecutorclient.ts
Bug fix for the following commit, https://github.com/SharePoint/PnP-JS-Core/commit/fe7299dd8fb57f37e2a450b91d2cbd955acef4d9
=> Body not included in request in SPRequestExecutorClient

src/sharepoint/rest/site.ts
When accessing another site collection from the current context, the returned ContextInfo was still using the current context.
new Site("https://contoso.sharepoint.com").getContextInfo().then((context: ContextInfo) => {
console.log(context);
})
=> Site ContextInfo fix

debug/debug.ts, src/configuration/pnplibconfig.ts, src/net/httpclient.ts, src/net/nodefetchclient.ts, src/types/index.ts, webpack-serve.config.js, webpack.config.js
| New feature?    | [ X]
Updates the config to allow one to set any HttpClientImpl at runtime using a factory function.
```
...
import { NodeFetchClient } from "../src/net/nodefetchclient";
...
// configure your node options
pnp.setup({
fetchClientFactory: () => {
return new NodeFetchClient(settings.testing.siteUrl, settings.testing.clientId, settings.testing.clientSecret);
}
});
```
=> Allow setting of custom HttpClientImpl

src/sharepoint/items.ts, src/sharepoint/odata.ts, src/sharepoint/queryable.ts
| Related issues?  | fixes #336 
Updates the way items.add handles the need to conditionally get the list item type name for the add operation. Moves that logic to a chained promise to allow us to have a clean return at the top keeping us inline with the main thread execution order so all our items are added to the batch before it is executed.
=> fix for issue 336 related to batching items.add

src/sharepoint/contenttypes.ts
| New feature?    | [ x]
JS Provisioning needs to be able to remove content types from a list instance in order to support RemoveExistingContentTypes.
=> Added delete method to ContentType

.babelrc
| Related issues?  | fixes #400
removes the babelrc file. We are no longer using babel and this was causing issues for some folks packaging things.
=> deleting .babelrc as babel is no longer used and was causing errors for folks

src/sharepoint/index.ts, src/sharepoint/relateditems.ts, src/sharepoint/webs.ts
| Related issues?  | fixes #397 
Adds support for managing related items. Chains off the Web object's relatedItems property.
=> Adding support for managing related items

src/sharepoint/search.ts
SearchPropertyValue can be of other types besides string as per https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.search.query.querypropertyvalue_members.aspx. Added all types and set them to optional so you can pick one.
=> Support all property types on search

src/configuration/pnplibconfig.ts
The upper letters "FX" in config.hasOwnProperty("spFXContext ") check in file src/configuration/pnplibconfig.ts were the reason the pnp.setup not to pick the custom spfxContext for spfx webpart. 
| Bug fix?        | [X ]
Small bug fix related to issue https://github.com/SharePoint/PnP-JS-Core/issues/411
=> config.hasOwnProperty check "spFXContext" string replaced by "spfxContext"

src/sharepoint/search.ts
I have added `SearchBuiltInSourceId` class for built in search result sources id constants. I also changed type of `SearchResults.PrimarySearchResults` from `any` to `any[]` - this allows to use array functions like `map()` without type casting.
=> Added SearchBuiltInSourceId class

gulptasks/publish.js, src/sharepoint/files.ts, src/sharepoint/index.ts, src/sharepoint/site.ts, tests/sharepoint/site.test.ts
| Related issues?  | fixes #422 
Adds support for the openWebById method. Usage:
```TypeScript
pnp.sp.site.openWebById("155cb453-90f5-482e-a380-cee1ff383a9e").then(ww => {
//we got all the data from the web as well
console.log(ww.data);
// we can chain
ww.web.select("Title").get();
});
```
=> Adding support for openWebById method on Site

src/sharepoint/utilities.ts
Removes a method from utility. This is not a breaking change as this method was never in a full release.
=> removing getLocalizedString from utility

src/net/digestcache.ts
| Related issues?  | fixes #464
=> Fixed issue with missing headers in digest request.

src/net/httpclient.ts
| Related issues?  | fixes #469 
Update to HttpClientImpl to not request the digest value when an Authorization header is already present in the supplied options.
=> Fix for #469

src/sharepoint/queryableshareable.ts
… seen it been true when sharing. Also PNP Csom external sharing example uses includeAnonymousLinkInEmail = false
| Bug fix?        | [x ]
Changed the default requireSignin to false, instead of true.
This is so includeAnonymousLinkInEmail is false by default.
I have never seen it be true when sharing. I've received errors while it being true.
And in PnP CSOM external sharing it is also set to false.
Hopefully this is correct, you can try it out :)
/Simon
=> I think requireSignin should be false instead of true by default

src/net/httpclient.ts, src/sharepoint/queryable.ts, src/sharepoint/rest.ts, src/types/index.ts, tests/mocks/mockfetchclient.ts, tests/sharepoint/configure.test.ts
| Related issues?  | References #499
This PR addresses referenced issue.   
If you want to apply custom header in any particular object, you can do:   
```javascript
let groups = pnp.sp.configure({
'myHeader': 'myvalue'
}, 'https://my.base.com').web.siteGroups;
```  
`groups` (as well as `web` and all other objects in a chain) object will hold additional header `myHeader` and this header will be attached to actual http request.  This approach allows you to send simultaneous requests with different headers or authentication information, for example:   
```javascript
let userAccessToken = 'Bearer eyJ0eXAiO...';
let appOnlyToken: = 'Bearer eyJ0eXAiO....';
let anotherUserAccessToken = 'Bearer eyJ0eXAiO....';
let user1 = …
```
=> Added a feature to apply custom headers and base url on a per-object basis

src/sharepoint/odata.ts, src/sharepoint/webs.ts, src/utils/util.ts
| Related issues?  | fixes #517
Fixes an issue when getting files/folders from sub webs the editLink isn't enough to create the correct path. Added use of metadata to ensure full absolute path.
=> Fix for #517, update extractWebId to use metadata and editLink

src/sharepoint/siteusers.ts
| Related issues?  | fixes #571
Adds aliasing for the querystring parameter so it chains properly and is not lost downstream.
=> fix for #571

src/sharepoint/items.ts
| Related issues?  | adds function mentioned in #580 
Adds support for passing the list item type full name as a param to item.update to match items.add. This reduces calls required in batched update scenario.
=> adding item type name as param in item.update as per #580

gulptasks/@configuration.js, gulptasks/build.js, gulptasks/package.js, src/pnp.ts
| Related issues?  | fixes #595
Moves all the exports back to the root level to work with Webpack
=> moving exports back to root of package to work in umd

src/sharepoint/attachmentfiles.ts
| Bug fix?        | N
| New feature?    | Y
| New sample?   | N
Added support to delete multiple attachments from a SharePoint list item by passing the file names. It make use of the `/AttachmentFiles/getByFileName('test.txt')` method 
Example:
```
const list = $pnp.sp.web.lists.getByTitle("MyList");
var fileInfos = ["1.txt","2.txt"];
list.items.getById(2).attachmentFiles.deleteMultiple(fileInfos).then(r => {
console.log(r);
});
```
=> Added support to delete multiple attachments

src/sharepoint/webs.ts
| Bug fix?        | [ N ]
| New feature?    | [ Y ]
| New sample?      | [ N ]
Added support for /_api/web/GetStorageEntity endpoint.
This addition will enable developers to get the tenant property set in the app catalog site by their key name.
For more information - [SharePoint Online Tenant Properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties)
Usage:
```
$pnp.sp.web.getStorageEntity('SPFxTestApiKey').then(r => {
console.log(r);
});
```
=> Added support for /_api/web/GetStorageEntity endpoint

src/sharepoint/items.ts
| Bug fix?            | [ ]
| New feature?   | [x]
| New sample?   | [ ]
When working with external lists, it's not possible to get list item with `lists.getByTitle('External List').items.getById(identity)`.
External list's item identity is a string (with format like '__bg40002300').
Currently, without feasibility of getting external lists' items by string id, it's not possible to update or delete such items and sometimes impossible to get item's data (depending on ECTs filter configuration).
External list items should be selected by BdcItentity in REST with `/_api/web/lists/getByTitle('External List')/getItemByStringId('__bg40002300')`.
This PR adds the capability of getting external lists items by `getItemByStringId` then working with an …
=> Adds capability of getting external lists items by `getItemByStringId`

src/sharepoint/webs.ts
| Bug fix?        | N
| New feature?    | Y
| New sample?      | N
Added support to get list of all available apps.
Added support to get a specify app by id.
Added support for app operations such as Install, Deploy, Uninstall, Upgrade, Retract and Remove events.
Reference - [alm-api-for-spfx-add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins)
=> Added support for ALM APIs

src/sharepoint/regionalsettings.ts, src/sharepoint/webs.ts, tests/sharepoint/regionalsettings.test.ts, tests/sharepoint/web.test.ts
| Related issues?  | implements #649
This PR implements `_api/web/RegionalSettings` endpoint.
```typescript
// Get regional setting
pnp.sp.web.regionalSettings.select('LocaleId,ShowWeeks').get().then(console.log);
// Get time zone
pnp.sp.web.regionalSettings.timeZone.get().then(console.log);
// Get time zones
pnp.sp.web.regionalSettings.timeZones.top(1).get().then(console.log);
// Get installed languages
pnp.sp.web.regionalSettings.installedLanguages.get().then(langs => {
console.log(langs.Items[0]);
});
```
=> RegionalSettings endpoint implementation, #649

src/sharepoint/userprofiles.ts
| Related issues?  | fixes #656
Fixes the issue with getPropertiesFor response type.
Was:
```typescript
public getPropertiesFor(loginName: string): Promise<any[]> {
const q = this.clone(UserProfileQuery, "getpropertiesfor(@v)");
q.query.add("@v", `'${encodeURIComponent(loginName)}'`);
return q.get();
}
```
Should be:
```typescript
public getPropertiesFor(loginName: string): Promise<any[]> {
const q = this.clone(UserProfileQuery, "getpropertiesfor(@v)");
q.query.add("@v", `'${encodeURIComponent(loginName)}'`);
return q.get();
}
```
=> getPropertiesFor typing issue fix

src/sharepoint/regionalsettings.ts, tests/sharepoint/regionalsettings.test.ts
| Related issues?  | mentioned in #659
The PR implements:
- Getting TimeZone by Id
- TimeZone/utcToLocalTime
- TimeZone/localTimeToUTC
```TypeScript
let regionalSettings = pnp.sp.web.regionalSettings;
let timeZone = await regionalSettings.timeZones.getById(15).get();
console.log(timeZone);
let date1 = '2017-12-08T13:20:00';
let { localTime } = await regionalSettings.timeZone.utcToLocalTime(date); // Receives Date or ISO String
console.log(localTime);
let date2 = new Date();
let { utcTime } = await regionalSettings.timeZones.getById(15).localTimeToUTC(date2 ); // Receives Date or ISO String
console.log(utcTime);
```
=> Implements TimeZone/utcToLocalTime and TimeZone/localTimeToUTC

src/sharepoint/lists.ts
| Related issues?  | fixes #671
Fixes the issue, described in #671 
Was testing it with [this script](https://github.com/koltyakov/PnP-JS-Core-Debug/blob/master/runners/renderListData.ts). In SharePoint Online, On-Prem 2013, also the same error was originally found while working with external lists.
@patrick-rodgers could you please take a look?
There was even a comment, that data should be a string (right above the line of code which fails trying parsing json string while it's an object).
=> RenderListData response processing issue #671 fix

src/sharepoint/search.ts
| New feature?    | [ x ]
Added Refiners to ResultTable interface (SharePoint search).
With Refiners added in this interface we can use these refiners as a result from a SharePoint search query.
=> Added Refiners to ResultTable interface (SharePoint Search)

src/sharepoint/attachmentfiles.ts
By default, when you delete an attachment, its permanently deleted and you can't recover the attachment.
These methods add support to send attachment(s) to recycle bin
| Bug fix?        | N
| New feature?    | Y
| New sample?      | N
| Related issues?  | NA
Support to send list item attachments to recycle bin
=> Added support to send attachments to recycle bin

src/sharepoint/lists.ts, tests/sharepoint/lists.test.ts
| Related issues?  | fixes #692
Fixes https://github.com/SharePoint/PnP-JS-Core/issues/692, the type of list's defaultView method should be `View`. So it's possible to chain the method with view-specific functionality.
=> defaultView now returns View not SharePointQueryableInstance

src/sharepoint/fields.ts, src/sharepoint/types.ts
| Related issues?  | fixes #697
Adds the ability to add a lookup field as well as a user field through the new addUser and addLookup methods.
=> adding support for addUser and addLookup methods on fields collection

src/sharepoint/fields.ts, src/sharepoint/types.ts
| Related issues?  | mentioned in #704 
Added the following methods to the Fields class:
addChoice
addMultiChoice
addBoolean
Also created a FieldCreationProperties interface which contains the most common field creation properties for sake of intellisense. It extends TypedHash<string | number | boolean> so other properties are also supported (no breaking change).
Also changed the type of the properties argument so that FieldTypeKind is mandatory (could be a breaking change? the FieldTypeKind property is required by the REST API anyway so this would only break already broken code I guess).
=> Added addChoice, addMultiChoice, addBoolean to Fields

src/sharepoint/webs.ts
| Bug fix?        | N
| New feature?    | Y
| New sample?      | N
| Related issues?  | NA
As mentioned in title, added support to get files and folders which contain % and # characters.
Usage:
To get a file with special character -
```
var url = "/sites/test/Shared Documents/" + encodeURIComponent("%123.docx");
$pnp.sp.web.getFileByServerRelativePath(url).get().then(r => {
console.log(r);
}); 
```
To get a folder with special character -
```
var url = "/sites/test/Shared Documents/" + encodeURIComponent("%123");
$pnp.sp.web.getFolderByServerRelativePath(url).get().then(r => {
console.log(r);
});
```
=>  Added support for % and # character in files and folders with the ResourcePath API

src/sharepoint/items.ts
Adds support for using skip token with backward direction.
```typescript
console.log(
await list.items.select('Id').skip(23).top(5).get()
.then(r => r.map(i => i.Id))
);
console.log(
await list.items.select('Id').skip(23, true).top(5).get()
.then(r => r.map(i => i.Id))
);
```
With this, it's possible to manage back page navigation being on a random paged data page.
=> Skip PagedPrev=TRUE support

src/sharepoint/files.ts
Adds `verbose` OData mode support for files.addChunked.
There was an issue when `odata=verbose` with `startUpload` and `continueUpload` responses treatment.
Also, `addChunked` returned incorrect object (data contained not a metadata but a File object):
this is fixed too.
=> addChunked verbose support and minor fixes

src/sharepoint/index.ts, src/sharepoint/rest.ts, src/sharepoint/social.ts, tests/sharepoint/social.test.ts
Added support for following endpoints:
```
_api/social.following/follow
_api/social.following/stopFollowing
_api/social.following/isFollowed
```
Example usage:
`pnp.sp.social.follow({ActorType: SocialActorType.Site, ContentUri: "https://siteUrl" });`
=> Added support for social.following endpoints

src/sharepoint/search.ts
Following #686 : Added Refiners to ResultTable for SharePoint Search;
The Name Property is added to the Refiners definition.
| Bug fix?        | 
| New feature?    |  x
| New sample?      |
The Name property is returned by the API. But it wasn't in the definitions.
=> Added Name to ResultTable Refiners definition.

src/sharepoint/userprofiles.ts
Added support for setting user profile properties using following endpoints:
```
/_api/SP.UserProfiles.PeopleManager/SetSingleValueProfileProperty
/_api/SP.UserProfiles.PeopleManager/SetMultiValuedProfileProperty
```
Example usage:
```
pnp.sp.profiles.setSingleValueProfileProperty("i:0#.f|membership|user@contoso.onmicrosoft.com", "AboutMe", "Lorem ipsum");
pnp.sp.profiles.setMultiValuedProfileProperty("i:0#.f|membership|user@contoso.onmicrosoft.com", "SPS-Skills", ["SharePoint", "Azure"]);
```
=> Added support for setting user profile properties

src/sharepoint/types.ts
Added missing options to [RenderListDataParameters](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.renderlistdataparameters_members.aspx) and [RenderListDataOptions](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.renderlistdataoptions.aspx) used in RenderListDataAsStream method.
=> Added missing options to RenderListDataParameters

src/sharepoint/items.ts
| Feature enhancement [ x ]
This commits add support for `expose` to the new `getAll` method.
We discussed this on gitter, and I understand that `expose` was deliberately excluded from `getAll` because of performance reasons. 
While I understand the decision I still would like the ability to get all data in the exact same was as with `items.get()`. My fix will re-use the original query, so it should "just work", even if the original query would change layout somehow (unlikely).
The reason I want this is that we often use pnp for small snippets (using [tick](https://www.npmjs.com/package/tick-cli)), and then we need to run `expose` to do one-time jobs where we need more data, even if they are slow.
P.S. I was originally suppose to just make an …
=> Add support for `expose` in `getAll`

src/sharepoint/clientsidepages.ts
| Related issues?  | fixes #741 
Removed the generic type parameter defaults from clientsidepages.ts to resolve issue #741.
=> fix for #741

src/sharepoint/files.ts
| Related issues?  | partially #758 
Adds uploadId to chunked progress interface, makes startUpload, continueUpload, and finishUpload protected.
=> quick update to assist with #758

src/sharepoint/webs.ts
| Q                        | A
| ------------------ | ---
| Bug fix?              | [X]
| New feature?     | [ ]
| New sample?     | [ ]
| Related issues?  | fixes #806 #784
Adds the addClientSidePageByPath method to the Web class allowing you to create a client side page using the library path.
=> adds the addClientSidePageByPath method to the Web class

src/sharepoint/types.ts
at line 361 some compilers fails due undefined is missing.
| Q                        | A
| ------------------ | ---
| Bug fix?              | [ x]
| New feature?     | [ ]
| New sample?     | [ ]
Rare compiler errors occurs due missing type at line 361.
Example error message : 'string | undefined' is not assignable to string index type 'string | number | boolean'.
It's not a issue but might be problematic for some new users.
=> fixed rare compiler error due type checkings

src/sharepoint/site.ts
| Q                        | A
| ------------------ | ---
| Bug fix?              | [ ]
| New feature?     | [X]
| New sample?     | [ ]
| Related issues?  | fixes #790
Adds a getRootWeb() method to Site class to get a Web instance correctly established for chaining.
=> Added getRootWeb method to Site class
